site_name: Voromesh
site_description: "Bounded Voronoi diagrams."

theme:
    name: "material"
    palette:
        primary: "blue"
        accent: "grey"

plugins:
    - search
    - mkdocstrings
    - mkdocs-jupyter:
        execute: true

markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences

nav:
    - "Start": index.md
    - "Bounded Voronoi diagram": helloworld.ipynb
    - "Extrusion of a surface mesh": structured.ipynb
    - "Voronoi mesh from GMSH mesh (Part 1)": mesh1.ipynb
    - "Mapping elevation data to Voronoi mesh (Part 2)": mesh2.ipynb
    - "A mesh for TOUGH3 (Part 1)": tough1.ipynb
    - "Mesh properties for TOUGH3 (Part 2)": tough2.ipynb
    - "API for class Voronoi": api_voronoi.md
    - "API of module geo": api_geo.md
    - "API of module tough3": api_tough3.md
